version: "3"
tasks:
  build:
    cmd: latexmk -pdf main.tex {{.LATEXMK_ARGS}}
  build-en:
    cmd: latexmk -pdf main-en.tex {{.LATEXMK_ARGS}}
  replace-punctuation:
    cmd: fd -e tex -x python3 scripts/replace-punctuation.py {}
vars:
  LATEXMK_ARGS: >-
    -synctex=1
    -interaction=nonstopmode
    -file-line-error
    -outdir=artifacts
